language: generic

sudo: requried
services:
  - docker
before_install:
  - docker build -t lobsters88/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true lobsters88/docker-react npm run test



